### ISSUE TITLE
Options to replace and exclude deps

### ISSUE THREAD

**Issue by marcelotrevisani** [regro/conda-press#20]
Hello guys!

I have been using ``conda-press`` for some days and I faced two improvements which would be nice to have.  :)

The first problem is, there are some dependencies which exist just in ``conda-forge`` or in the main packages. If I use ``conda-press`` to convert it, the wheel will try to install that dependency. For example, ``Caffe`` is a package which we have on ``conda-forge`` but we don't have it on ``PyPI``.

It would be good to have an option such as ``--exclude-dep`` which accepts a list of deps we may exclude.

The second problem might be related to the first one, some dependencies have different names in ``conda-forge``/``main`` and in ``PyPI``. For example, ``OpenCV`` is just ``OpenCV`` on ``conda-forge`` but it is different on ``PyPI``, which is ``OpenCV-python``. It would be interesting to have an option to replace some dependencies name or allied with the ``--exclude-dep`` we might have an option ``--add-dep`` which also accepts a list of packages to be added to the wheel.

I might try to develop it during this weekend, but if someone already knows how to implement it. It is fine for me!  :)

cc: @scopatz

**Comment by scopatz** [comment]
Hi @marcelotrevisani! Sorry for the slow response; I was on vacation.

I think either / both of those options would be great to have. In general, it would be nice to be able to provide a mapping from the "conda name" of a package to the "pypi" name of the package.  Maybe this could live on the command line and/or in a sidecar file somewhere.  Note that it would definitely need to be something that is overrideable because conda-press can be used with channels that are not conda-forge and be targeting package indexes that aren't pypi.org.

**Comment by scopatz** [comment]
Also, note that if we wanted a general mapping, the conda packages themselves *usually* contain the pypi.org name in the source code url.  We could try to generate and maintain a list with one of the bots. That will come later, though. The functionality needs to be in conda-press first.

**Comment by marcelotrevisani** [comment]
Closing this in favor of #23 and #26
